parameters:
#    sk_mon_premier.example.class: SK\MonPremierBundle\Example

services:
#    sk_mon_premier.example:
#        class: %sk_mon_premier.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
